"""Initial migration

Revision ID: 0b705dc0eed6
Revises: 61d94b666998
Create Date: 2025-12-21 14:14:05.776079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b705dc0eed6'
down_revision = '61d94b666998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swap_offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offerer_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('offered_product_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=True))
        batch_op.drop_constraint(batch_op.f('swap_offers_buyer_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('swap_offers_offering_product_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['offered_product_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['offerer_id'], ['id'])
        batch_op.drop_column('buyer_id')
        batch_op.drop_column('offering_product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swap_offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offering_product_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('buyer_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('swap_offers_offering_product_id_fkey'), 'products', ['offering_product_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('swap_offers_buyer_id_fkey'), 'users', ['buyer_id'], ['id'])
        batch_op.drop_column('message')
        batch_op.drop_column('offered_product_id')
        batch_op.drop_column('offerer_id')

    # ### end Alembic commands ###
