"""Swap offer tablosu eklendi

Revision ID: 8b728f02428f
Revises: 0b705dc0eed6
Create Date: 2025-12-22 18:29:36.520457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b728f02428f'
down_revision = '0b705dc0eed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('swap_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offerer_id', sa.Integer(), nullable=False),
    sa.Column('target_product_id', sa.Integer(), nullable=False),
    sa.Column('offered_product_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['offered_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['offerer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swap_offers')
    # ### end Alembic commands ###
